# Generated by Django 5.2.4 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='url',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
