# Generated by Django 4.2.23 on 2025-07-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0003_habilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
