# Generated by Django 5.2.4 on 2025-07-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0005_estudio_experiencialaboral_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadBlanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Habilidad Blanda',
                'verbose_name_plural': 'Habilidades Blandas',
            },
        ),
        migrations.AddField(
            model_name='habilidad',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
