# Generated by Django 5.2.4 on 2025-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0006_habilidadblanda_habilidad_icono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidadblanda',
            options={'verbose_name': 'Habilidad blanda', 'verbose_name_plural': 'Habilidades blandas'},
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='icono',
            field=models.TextField(help_text='Código HTML de icono (SVG o <i> de Bootstrap)'),
        ),
        migrations.AlterField(
            model_name='habilidadblanda',
            name='icono',
            field=models.TextField(help_text='Código HTML de icono (SVG o <i> de Bootstrap)'),
        ),
    ]
