# Generated by Django 5.2.4 on 2025-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0007_alter_habilidadblanda_options_alter_habilidad_icono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='icono',
            field=models.TextField(help_text='Código HTML para el icono (SVG o <i> de Bootstrap).'),
        ),
        migrations.AlterField(
            model_name='habilidadblanda',
            name='icono',
            field=models.TextField(help_text='Código HTML para el icono (SVG o <i> de Bootstrap).'),
        ),
    ]
